/**
 * OPTIONAL / non-default — not used for current launch.
 *
 * Product default is pure cold start: no backfill, no founding wall, ~122 historical
 * commit authors are Spark @ 0 until their first post-launch qualifying event.
 *
 * ---
 * Initialize the Founding Contributor wall (legacy option B).
 *
 * - Fetches all current commit contributors from nexu-io/open-design
 * - Marks anyone with >= MIN_COMMITS as `founding: true` in data/contributors.json
 * - Does NOT grant any points (forward-only model)
 * - Generates the initial CONTRIBUTORS.md with a "Founding Contributors" header
 *
 * Run once before v1 goes live. Idempotent: re-running won't double-count.
 *
 * Run manually if ever needed:
 *   pnpm exec tsx scripts/init-founding-wall.ts
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { App } from "octokit";

const MIN_COMMITS_TO_BE_FOUNDING = 5;
const OUT_JSON = "data/contributors.json";
const OUT_MD = "CONTRIBUTORS.md";

interface Contributor {
  username: string;
  avatarUrl: string;
  points: number;
  tier: "spark";
  prsMerged: number;
  reviews: number;
  discussionsAnswered: number;
  issuesAccepted: number;
  streakWeeks: number;
  lastActiveAt: string;
  founding: boolean;
  foundingCommits?: number;
  tierHistory: Array<{ tier: string; reachedAt: string }>;
}

function loadDevVars(path: string): Record<string, string> {
  const out: Record<string, string> = {};
  let buffer = "", currentKey: string | null = null, inMultiline = false;
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    if (inMultiline) {
      if (line.endsWith('"') && !line.endsWith('\\"')) {
        buffer += line.slice(0, -1);
        out[currentKey!] = buffer;
        currentKey = null; buffer = ""; inMultiline = false;
      } else { buffer += line + "\n"; }
      continue;
    }
    const m = line.match(/^([A-Z_][A-Z0-9_]*)\s*=\s*"(.*)$/);
    if (!m) continue;
    const [, key, rest] = m as unknown as [string, string, string];
    if (rest.endsWith('"') && !rest.endsWith('\\"')) {
      out[key] = rest.slice(0, -1);
    } else {
      currentKey = key; buffer = rest + "\n"; inMultiline = true;
    }
  }
  return out;
}

async function fetchAllContributors(octokit: any): Promise<Array<{ login: string; avatar_url: string; contributions: number }>> {
  const all: Array<{ login: string; avatar_url: string; contributions: number }> = [];
  let page = 1;
  while (true) {
    const r = await octokit.rest.repos.listContributors({
      owner: "nexu-io",
      repo: "open-design",
      per_page: 100,
      page,
    });
    if (r.data.length === 0) break;
    for (const c of r.data) {
      if (c.type !== "User" || !c.login) continue;
      all.push({
        login: c.login,
        avatar_url: c.avatar_url ?? "",
        contributions: c.contributions ?? 0,
      });
    }
    if (r.data.length < 100) break;
    page++;
  }
  return all;
}

function buildMarkdown(file: { contributors: Record<string, Contributor> }): string {
  const all = Object.values(file.contributors);
  const founding = all.filter((c) => c.founding).sort((a, b) => (b.foundingCommits ?? 0) - (a.foundingCommits ?? 0));
  const active = all.filter((c) => !c.founding && c.points > 0).sort((a, b) => b.points - a.points);

  const lines: string[] = [];
  lines.push("# Open Design Contributors");
  lines.push("");
  lines.push("> Auto-generated by [open-design-bot](https://github.com/nexu-io/open-design-bot). Do not edit by hand.");
  lines.push("");
  lines.push("## 🌱 Founding Contributors");
  lines.push("");
  lines.push("These are the people who built Open Design from day one — long before the points system existed. They are recognized in perpetuity, regardless of future activity.");
  lines.push("");
  lines.push("| | Contributor | Commits before launch |");
  lines.push("|---|---|---|");
  for (const c of founding) {
    lines.push(`| <img src="${c.avatarUrl}" width="32" /> | [@${c.username}](https://github.com/${c.username}) | ${c.foundingCommits ?? 0} |`);
  }
  lines.push("");
  lines.push(`*${founding.length} founding contributors as of ${new Date().toISOString().slice(0, 10)}*`);
  lines.push("");
  lines.push("## 🏆 Active Leaderboard");
  lines.push("");
  if (active.length === 0) {
    lines.push("*No tracked activity yet — be the first to merge a PR after launch and you'll appear here!*");
  } else {
    lines.push("| Rank | Tier | Contributor | Points | Streak | PRs | Reviews |");
    lines.push("|---|---|---|---|---|---|---|");
    active.forEach((c, i) => {
      lines.push(`| #${i + 1} | ${c.tier} | <img src="${c.avatarUrl}" width="24" /> [@${c.username}](https://github.com/${c.username}) | ${c.points} | ${c.streakWeeks > 0 ? `🔥 ${c.streakWeeks}w` : "—"} | ${c.prsMerged} | ${c.reviews} |`);
    });
  }
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const vars = loadDevVars(join(process.cwd(), ".dev.vars"));
  const app = new App({ appId: vars.GH_APP_ID!, privateKey: vars.GH_APP_PRIVATE_KEY! });
  const octokit = await app.getInstallationOctokit(Number(vars.GH_APP_INSTALLATION_ID));

  console.log("Fetching all commit contributors...");
  const fetched = await fetchAllContributors(octokit);
  console.log(`  → ${fetched.length} unique commit contributors`);

  let file: { generatedAt: string; totalContributors: number; contributors: Record<string, Contributor> };
  if (existsSync(OUT_JSON)) {
    file = JSON.parse(readFileSync(OUT_JSON, "utf8"));
  } else {
    file = { generatedAt: new Date().toISOString(), totalContributors: 0, contributors: {} };
  }

  let foundingCount = 0;
  const now = new Date().toISOString();
  for (const c of fetched) {
    if (c.contributions < MIN_COMMITS_TO_BE_FOUNDING) continue;
    foundingCount++;
    const existing = file.contributors[c.login];
    if (existing) {
      existing.founding = true;
      existing.foundingCommits = c.contributions;
      if (!existing.avatarUrl) existing.avatarUrl = c.avatar_url;
    } else {
      file.contributors[c.login] = {
        username: c.login,
        avatarUrl: c.avatar_url,
        points: 0,
        tier: "spark",
        prsMerged: 0,
        reviews: 0,
        discussionsAnswered: 0,
        issuesAccepted: 0,
        streakWeeks: 0,
        lastActiveAt: now,
        founding: true,
        foundingCommits: c.contributions,
        tierHistory: [{ tier: "spark", reachedAt: now }],
      };
    }
  }

  file.totalContributors = Object.keys(file.contributors).length;
  file.generatedAt = now;

  writeFileSync(OUT_JSON, JSON.stringify(file, null, 2));
  writeFileSync(OUT_MD, buildMarkdown(file));

  console.log("");
  console.log("✅ Founding wall initialized");
  console.log(`   ${foundingCount} founding contributors (≥ ${MIN_COMMITS_TO_BE_FOUNDING} commits)`);
  console.log(`   ${OUT_JSON} written`);
  console.log(`   ${OUT_MD} written`);
  console.log("");
  console.log("Next: review locally, then commit + push to nexu-io/open-design.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
